### PR TITLE
2.1 release missing file: CpQueryFilterLexer.java and CpQueryFilterParser.java

### PR DESCRIPTION
**Pull request by heartmoving**
hello,I get 2.1 release code,Not found CpQueryFilterLexer.java and CpQueryFilterParser.java
like this:
missing
please tell me where can get it,thanks!

### CODE REVIEW

**Comment by heartmoving** [comment]
hello,I find CpQueryFilterLexer.java and CpQueryFilterParser.java from e2e release ，under org\apache\usergrid\persistence\index\query\tree ,I copy these files to 2.1 release,this error is ok,thanks.

**Comment by maysam1986** [comment]
I have the same problem. Also I can not find those two files (CpQueryFilterLexer.java and CpQueryFilterParser.java) in the e2e or any other releases. Please kindly Give me some advice.
untitled

**Comment by MattW86** [comment]
Why are these files in the gitignore?

**Comment by snoopdave** [comment]
Those two files are generated by the ANTLR parser generator as part of the build process.

It would be much better for the build process to put those two files into a directory on der the target directory, e.g. "target/generated" so they do not cause problems, and don't have to be ignored.

**Pull request closed without merging**
